apiVersion: v1
kind: ConfigMap
metadata:
  name: blnk-config
  namespace: blnk
data:
  blnk.json: |
    {
      "project_name": "Blnk",
      "data_source": {
        "dns": "postgres://postgres:password@postgres:5432/blnk?sslmode=disable"
      },
      "redis": {
        "dns": "redis:6379"
      },
      "server": {
        "port": "5001"
      }
    } 