apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml -o k8s-manifests/
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: server
  name: server
  namespace: blnk
spec:
  type: LoadBalancer                # ← expose externally via a GCP LB
  ports:
    - name: "5001"
      port: 5001
      targetPort: 5001
    - name: "80"
      port: 80
      targetPort: 80
    - name: "443"
      port: 443
      targetPort: 443
  selector:
    io.kompose.service: server
status:
  loadBalancer: {}
