apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml -o k8s-manifests/
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: typesense
  name: typesense
  namespace: blnk
spec:
  ports:
    - name: "8108"
      port: 8108
      targetPort: 8108
  selector:
    io.kompose.service: typesense
status: {} 